name: Develop in a branch
on: [pull_request, workflow_dispatch]
jobs:
    job1:
        name: Job 1
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Workflow triggered in branch ${{ github.ref }}."
                echo "Workflow triggered by actor ${{ github.actor }}."
                echo "Workflow triggered by event ${{ github.event }}."
